version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install for static site"
  build:
    commands:
      - echo "Build phase - nothing to build for static site"

artifacts:
  files:
    - '**/*'
